version: '3.8'
services:
  app:
    container_name: "application-server"
    hostname: app
    image: "mintplexlabs/anythingllm:latest"
    ports:
      - '3001:3001'
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    restart: always
    environment:
    # Adjust for your environemnt
      - STORAGE_DIR=/app/server/storage
    volumes:
      - .:/workspace:cached
      - work:/app/server/storage:cached
networks:
  app-network:
    external: true
