version: '2.4'
services:
  app:
    container_name: "application-server"
    image: "heartexlabs/label-studio:latest"
    restart: always
    volumes:
      - ..:/workspace:cached
    ports:
      - '8080:8080'
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    # command: /bin/sh -c "while sleep 1000; do :; done"
networks:
  app-network:
    external: true





